import { Lists, Summaries, Image, TextObject, Urls } from '../types'

export interface MarvelData {
    code: number,
    status: string,
    copyright?: string,
    attributionText?: string,
    attributionHTML?: string,
    data?: DataContainer,
    etag?: string

}

export interface DataContainer {
    offset: number,	
    limit: number,
    total: number,
    count: number,
    results: any,
}


export interface Characters {
    id: number,
    name: string,
    description?: string,
    modified?: string,
    resourceURI?: string,
    urls?: Urls[]
    thumbnail?: Image,
    comics?: Lists,
    stories?: Lists,
    events?: Lists,
    series?: Lists,
} 
export interface Comics{
    id: number,
    digitalId?: number,
    title: string,
    issueNumber?: number,
    variantDescription?: string,
    description?: string,
    modified?: string,
    isbn?: string,
    upc?: string,
    diamondCode?: string,
    ean?: string,
    issn?: string,
    format?: string,
    pageCount?: number,
    textObjects?: TextObject[],
    resourceURI?: string,
    urls?: Urls[],
    series?: Summaries,
    variants?: Summaries[],
    collections?: Summaries[],
    collectedIssues?: Summaries[],
    dates?: Summaries[]
    prices?: Summaries[],
    thumbnail?: Image,
    images?: Image[],
    creators?: Lists,
    characters?: Lists,
    stories?: Lists,
    events?: Lists,
}
export interface Creators {
    id?: number,
    firstName?: string,
    middleName?: string,
    lastName?: string,
    suffix?: string,
    fullName?: string,
    modified?: string,
    resourceURI?: string,
    urls?: Urls[],
    thumbnail?: Image,
    series?: Lists,
    stories?: Lists,
    comics?: Lists,
    events?: Lists,
}
export interface Events {
    id: number,
    title: string,
    description?: string,
    resourceURI?: string,
    urls?: Urls[],
    modified?: string,
    start?: string,
    end?: string,
    thumbnail?: Image,
    comics?: Lists,
    stories?: Lists,
    series?: Lists,
    characters?: Lists,
    creators?: Lists,
    next?: Summaries,
    previous?: Summaries,
}
export interface Series {
    id: number,
    title: string,
    description?: string,
    resourceURI?: string,
    urls?: Urls[],
    startYear?: number,
    endYear?: number,
    rating?: string,
    modified?: string,
    thumbnail?: Image,
    comics?: Lists,
    stories?: Lists,
    events?: Lists,
    characters?: Lists,
    creators?: Lists,
    next?: Summaries,
    previous?: Summaries,
}
export interface Stories {
    id: number,
    title: string,
    description?: string,
    resourceURI?: string,
    type?: string,
    modified?: string,
    thumbnail?: Image,
    comics?: Lists,
    series?: Lists,
    events?: Lists,
    characters?: Lists,
    creators?: Lists,
    originalissue?: Summaries,
}